---
title: "Task2_Studentdata"
author: "Bhagyashree Khabale"
date: "09/09/2020"
output: html_document
---

Step1
Importing Student dataset into.csv file and Check the structure of the dataset

```{r}
library(datasets)
str(Student)
summary(Student)
```

#Step2
# Creating a model for predicting the Students Scores w.r.t. No of Hours
library(caTools)
set.seed(2)
split=sample.split(Student,SplitRatio = 0.7)
train=subset(Student,split="True")
test=subset(Student,split="False")
#Step3
# Creating Regression model (y=Scores,x=Hours)
model=lm(Scores~Hours,data = train)
summary(model)
#Step4
# Checking the predicted value
predict_result=predict(model,test)
result=cbind(test,preddict_result)
#Step5
#Plotting scatter data of Scores and Hours
library(ggplot2)
y=Student$Scores
x=Student$Hours
plot(x,y,ylab = "Scores",xlab = "No.of Hours",main = "Scores vs Hours")
#Step6
# Plotting best fit line
abline(lm(y~x))
#Step7
# Calculating Sum of Error of Square
SSE=sum((test$Scores-predict_result)^2)
SSE
#calculating Total sum of square of Error
SST=sum((test$Scores-mean(Student$Scores))^2)
SST
#Calculating Rss value
r=1-(SSE/SST)
r
#Output
Accuracy of the Model is:95.29%
For 9.2 hours prdicted Score will be 92.49%
